builds:
  -
    binary: docker-builder
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64

archives:
  -
    format: zip
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: x86
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "snapshot"

release:
  disable: false
  github:
    owner: qiushihe
    name: docker-builder

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
